spring:
  application:
    name: ms-registry-service  #  Nombre del microservicio. Es usado por Spring Cloud para identificar este servicio
    # en el Config Server (por ejemplo buscar치 "ms-registry-service-development.yml").

  profiles:
    active: development        # Perfil activo: indica que se usar치 la configuraci칩n con el perfil "development".
      # Entonces buscar치 el archivo remoto "ms-registry-service-development.yml"
    # dentro del repositorio config-data.

  config:
    import: optional:configserver:http://root:123456@localhost:7070
      # 游댕 Se importa configuraci칩n externa desde el Config Server (localhost:7070).
      # La palabra "optional:" evita que el proyecto falle si el servidor de configuraci칩n
      # no est치 disponible al arrancar.
    # Se incluye autenticaci칩n b치sica (usuario: root, contrase침a: 123456).
